; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Tue Nov 29 2022 22:47:54 GMT+0000 (Greenwich Mean Time)
G29 S2 ; turn of any mesh levelling

M98 P"homez.g"
M98 P"homex.g"
M98 P"homey.g"



