; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Tue Nov 29 2022 22:47:55 GMT+0000 (Greenwich Mean Time)
G91               ; relative positioning
G1 H1 X-503 F3600 ; move quickly to X axis endstop and stop there (first pass)
if move.axes[0].machinePosition <= -503
    set set global.xLF =1
    abort
G1 H2 X5 F6000    ; go back a few mm
G1 H1 X-6 F600  ; move slowly to X axis endstop once more (second pass)
G1 H2 X5 F6000
G90               ; absolute positioning