; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Tue Nov 29 2022 22:47:55 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0 S10

